version: '3.8'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    volumes:
      - .:/workspace
    environment:
      - DEBIAN_FRONTEND=noninteractive

networks:
  default:
    external:
      name: host  # Explicitly name the network